# Generated by Django 4.2.16 on 2025-06-03 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0003_flashcard_hidden_by_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_flashcard_set_limit', models.PositiveIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
        migrations.RenameField(
            model_name='flashcardset',
            old_name='rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='is_hidden',
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='total_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.flashcardset'),
        ),
        migrations.CreateModel(
            name='FlashcardSetRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='flashcards.flashcardset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('flashcard_set', 'user')},
            },
        ),
    ]
