# Generated by Django 5.2.3 on 2025-06-24 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_platformsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytelemetry',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studytelemetry',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studytelemetry',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studytelemetry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studytelemetry',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
